# Generated by Django 5.0.3 on 2024-09-11 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkopoApp', '0005_alter_loan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'ordering': ['payment_date']},
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='year',
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
