# Generated by Django 5.0.3 on 2024-09-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_adminconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminConfig',
        ),
    ]
