# Generated by Django 5.0.3 on 2024-09-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtajiApp', '0004_alter_mtaji_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtaji',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
