# Generated by Django 5.0.3 on 2024-07-21 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michangoApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='michango',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='michango',
            unique_together={('user', 'year', 'month')},
        ),
    ]
