# Generated by Django 5.0.3 on 2024-08-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michangoApp', '0002_alter_michango_month_alter_michango_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='michango',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='michango_screenshots/'),
        ),
    ]
