# Generated by Django 5.0.3 on 2024-08-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('michangoApp', '0003_michango_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='michango',
            name='screenshot',
        ),
    ]
